apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
  name: app-ui
spec:
  rules:
  - host: new.app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-ui
            port:
              number: 80
